export const PERMISSION_MODULES = [
  { id: 'sales', label: 'Salg & Tilbud' },
  { id: 'customers', label: 'Kunder' },
  { id: 'projects', label: 'Projekter' },
  { id: 'finance', label: 'Økonomi' },
  { id: 'planning', label: 'Planlægning' },
  { id: 'tasks', label: 'Opgaver' },
  { id: 'materials', label: 'Materialer & Lager' },
  { id: 'equipment', label: 'Materiel & Udstyr' },
  { id: 'employees', label: 'Medarbejdere' },
  { id: 'suppliers', label: 'Leverandører' },
  { id: 'quality', label: 'Kvalitet & Sikkerhed' },
  { id: 'environment', label: 'Miljø & Affald' },
  { id: 'service', label: 'Service & Abonnementer' },
  { id: 'documents', label: 'Dokumenter & Viden' },
  { id: 'company', label: 'Firma' },
  { id: 'screens', label: 'Skærme' },
];

export const ALWAYS_ALLOWED_PATHS = new Set([
  '/dashboard',
  '/admin',
  '/admin-portal',
  '/brugerprofil',
  '/app',
  '/app/tid',
  '/app/opgaver',
  '/app/beskeder',
  '/app/bilag',
  '/app/profil',
]);

export const ROUTE_PERMISSION_OVERRIDES = {
  '/Invoices': 'finance',
  '/invoices': 'finance',
  '/udstyr': 'equipment',
  '/maskinpark': 'equipment',
  '/projekt-galleri': 'projects',
  '/projektoverblik': 'projects',
  '/projekt-oversigt': 'projects',
  '/projekt-arkiv': 'projects',
  '/projekt-milepaele': 'projects',
  '/projekt-tidslinje': 'projects',
  '/projekt-logbog': 'projects',
  '/projektnotater': 'projects',
  '/projekt-budget': 'projects',
  '/projekt-tidsplan': 'projects',
  '/drifts-logbog': 'projects',
  '/kontaktliste': 'customers',
  '/kundeoversigt': 'customers',
  '/kundestatistik': 'customers',
  '/kundehenvendelser': 'customers',
  '/kundereferencer': 'customers',
  '/kundetilfredshed': 'customers',
  '/kundesupport': 'customers',
  '/kundekontakt-log': 'customers',
  '/kundearkiv': 'customers',
  '/tilbudsskabeloner': 'sales',
  '/tilbuds-beregner': 'sales',
  '/tilbudsanalyse': 'sales',
  '/salgsstatistik': 'sales',
  '/timepris-beregner': 'sales',
  '/adresse-opslag': 'sales',
  '/materialeindkoeb': 'materials',
  '/indkoebsliste': 'materials',
  '/indkoebsordrer': 'materials',
  '/indkoebskurv': 'materials',
  '/indkoebsordre': 'materials',
  '/materiale-lager': 'materials',
  '/lager-overblik': 'materials',
  '/lagerbeholdning': 'materials',
  '/lager-status': 'materials',
  '/materiel-lokationer': 'equipment',
  '/materiel-booking': 'equipment',
  '/materiel-vedligehold': 'equipment',
  '/materieludlejning': 'equipment',
  '/materiel-oversigt': 'equipment',
  '/udstyrsudlejning': 'equipment',
  '/udstyrs-booking': 'equipment',
  '/materiel-logistik': 'equipment',
  '/udstyrs-historik': 'equipment',
  '/vaerksted': 'equipment',
  '/vaerktoej-logbog': 'equipment',
  '/vaerktoej-liste': 'equipment',
  '/bilpark-oversigt': 'equipment',
  '/medarbejder-arkiv': 'employees',
  '/medarbejder-cv': 'employees',
  '/personale-oversigt': 'employees',
  '/medarbejder-administration': 'employees',
  '/medarbejderliste': 'employees',
  '/medarbejder-dashboard': 'employees',
  '/timeseddel-rapport': 'employees',
  '/tids-rapporter': 'employees',
  '/kursusstyring': 'employees',
  '/kursus-oversigt': 'employees',
  '/certifikat-kontrol': 'employees',
  '/certifikat-log': 'employees',
  '/certifikat-arkiv': 'employees',
  '/certifikat-overvaagning': 'employees',
  '/timebank-oversigt': 'employees',
  '/kompetence-matrix': 'employees',
  '/loenseddel-oversigt': 'employees',
  '/bemandings-plan': 'employees',
  '/leverandoeroversigt': 'suppliers',
  '/underentreprenorer': 'suppliers',
  '/subunderleverandoerer': 'suppliers',
  '/underleverandoerer': 'suppliers',
  '/underleverandoer-oversigt': 'suppliers',
  '/leverandoer-katalog': 'suppliers',
  '/leverandoer-styring': 'suppliers',
  '/afvigelsesrapport': 'quality',
  '/afvigelsesrapporter': 'quality',
  '/afvigelses-registrering': 'quality',
  '/afvigelsesstyring': 'quality',
  '/sikkerhedsprotokoller': 'quality',
  '/sikkerhedsinstruktioner': 'quality',
  '/sikkerhedsarkiv': 'quality',
  '/sikkerheds-logbog': 'quality',
  '/SikkerhedApv': 'quality',
  '/mangel-liste': 'quality',
  '/kvalitetsstyring': 'quality',
  '/kvalitetskontrol': 'quality',
  '/kvalitetsrapport': 'quality',
  '/kvalitetsstyring-oversigt': 'quality',
  '/forsikringssager': 'quality',
  '/asbest-dokumentation': 'environment',
  '/affalds-log': 'environment',
  '/servicekatalog': 'service',
  '/servicehistorik': 'service',
  '/vedligeholdelseslog': 'service',
  '/dokumentarkiv': 'documents',
  '/vidensbase-filer': 'documents',
  '/dokumentcenter': 'documents',
  '/portal/knowledgebase': 'documents',
  '/admin/knowledgebase': 'documents',
  '/digital-signatur': 'documents',
  '/virksomhedsindstillinger': 'company',
  '/firma-indstillinger': 'company',
  '/firma-profil': 'company',
  '/marketing-kampagner': 'company',
  '/noegletal': 'company',
  '/driftsbudget': 'company',
  '/driftsoekonomi': 'company',
  '/drifts-rapport': 'company',
  '/oekonomisk-status': 'company',
  '/regnskab-integration': 'finance',
  '/regnskab-program': 'finance',
  '/regnskab-kontoplan': 'finance',
  '/regnskab-rapporter': 'finance',
  '/regnskab-aarsoversigt': 'finance',
  '/daekningsbidrag': 'finance',
  '/udgifts-oversigt': 'finance',
  '/udlaegsstyring': 'finance',
  '/udgifts-godkendelse': 'finance',
  '/faktura-arkiv': 'finance',
  '/faktura-scan': 'finance',
  '/oekonomisk-oversigt': 'finance',
  '/moms-regnskab': 'finance',
  '/vejr-planlaegning': 'planning',
  '/moede-kalender': 'planning',
  '/moedeoversigt': 'planning',
  '/ressource-planlaegning': 'planning',
  '/ressource-kalender': 'planning',
  '/opgave-prioritering': 'tasks',
  '/opgavestyring': 'tasks',
  '/skadesrapport': 'quality',
  '/teknisk-isolering-beregner': 'sales',
};

export function normalizePermissions(permissions) {
  if (Array.isArray(permissions)) return permissions.filter(Boolean);
  if (typeof permissions === 'string' && permissions.trim()) {
    try {
      const parsed = JSON.parse(permissions);
      return Array.isArray(parsed) ? parsed.filter(Boolean) : [];
    } catch {
      return [];
    }
  }
  return [];
}

export function hasModuleAccess(user, moduleId) {
  if (!moduleId) return true;
  if (user?.role === 'admin') return true;
  if (user?.role === 'customer') return false;
  if (user?.permissions == null) return true;
  const permissions = normalizePermissions(user?.permissions);
  return permissions.includes(moduleId);
}

export function pathToPermission(pathname, groups = []) {
  if (ALWAYS_ALLOWED_PATHS.has(pathname)) return null;
  const group = groups.find((entry) => entry.items?.some((item) => item.to === pathname));
  return group?.permission || ROUTE_PERMISSION_OVERRIDES[pathname] || null;
}
